language: scala
dist: trusty
sudo: false
scala:
- 2.12.4
jdk:
- openjdk8
branches:
  only:
  - master
  - dev
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - secure: MQ7z1QJMYrj5BvE6zENtZQd4DYus/zMMjWkcyEscRzP8AU8u/OJ1MlRn0bfMcU0GXzLIWxTr+5zGGPa3ujeFNfK8HfSMpew4iLkurSnnL/nVxE2JdkVYjyJ28tJUgn2TemsUm29DJeAKDWoEIXesncOm+L6mvNf1k9t38Ks98slz+DQHjQrZbtnexsnKeaZoRPww7s8S9oNHO21cicygAZxW8yJWyc17VnOAcw93YDZT95HQy8o0jzvK3F8gePvPleWnZBl/77aJXS95fgEGXAvkzykOyUgdDcPdzOpBf/4cbDTXW/I/hXHkU7uYIRdJbE7DjNBouvYoPK36sdrOI/za186EL6J4Xx0XmRN55CzavFgGz0VoqWRNBPcKN2BiYL+mhyRRmpqSt38hpdMy0B6LpM7VMfz13peY3/u1oqRLIDe3ai9Spa2ZUs5WZidmhEqdaHXH1L5PXG1iJrRir0cnHA0L1QllveB5uZCPgdA1jz1PLWyyLH6lUR3ZEJyHX3zlbYdX57hSkZX2hcvPi9htfz2Y/ebwWP+jv1qMFir98VHDV1fEZWP2jaLh+djqy/Kb0WbtJHXu/Qidw/biKULayVMSJqGgRvRcNHrt6+fAWbweUb91eMFxnu9hcFzAWo9P5fH5OrzTFp0Y4vObYeY/Bx9+yPBXmfn3ALrTaio=
  - secure: FF36oz2pvy/7lLpsGnzBBuhgtFKluEvw+2i/Q0koygdOZBnwST0vClEeFfyLW0HdQFWSYUao2nePnlv+dR+FwYLmYgwupXWYfmCcLwPCyCQYIJwUcFwdFqwg3dlSFDWyqgj7fClfJCFzwKGfvNOLqEmNtyVXDk7gnb72ZYbOoY/3mQL+Y60CEmJIfW4xV0InjUQoE5KtNe+TxuHRKrfNbWEuu470mU9EVijQVa8Y/Rt7pQHPrfY/LQt8dODJMscbrGAawqWRo+58w8DGg/CoBFc/x7AvU61D3Pk2gdM8N9bt6s0w6lzcAGZoluskmXHqC9q0gtl9M74ml63kpHE8S/T2dRDk7mWCaW6ECfWLwJOOVPTB2gkTRxocBV5OuxGRG+jTvyCkc7HvA2+N8G4AEKBic5qB6aiA6pdWcTiscqzNZt7y7oGT1CgCW+7xkiOY+BbGE7Lj4qCaeRes+85Jn44SvYijh+hwapSvLVMCHJEVzkAmm4WtXbYem9VmPhfU1fQG3ePjgzgH9AVVT590E/z4GU5wUflNrlb3A1Wuy0E6TuHdB7tMHak0qmsq+1LHzNgQGPKMoazkG6MZ3OEO/tsw7GO7LfTeCfopR8YXR3F8XwLfkWJh5KPS2oQtIuHvneJMY8JxZLXK2CEkQNiKCByW+vR+Fad82hdR1/p+hAM=
  - secure: Nduz00ClOjYNgEOvrEtvUv5AYcB+30LoCLR/Sb2p+Ua/5PTNyy+hlxgRy1kHGG42HGfK1zeSmB2eUYUMN3og5Q6hmi4CHSzQDRjc9UC8DxjE9Bh9BPnriTkiG6wJlDmFEt4d7bqi/Z+Hpe6BfgLntm/lz8HaL2tewGP6EYsgB4DjZK5mM3F1R7OUDkSONkZGJMmzxdkv0pXEbow3oJv49muevWTObXzaOq31pEc8VVqDrbgnj1RNK6GRTCdA7enL8iLw7E30XIe8nm0R9NixW6C5Bs/fK+vSxCJ545sUHo60D0B2ze4Nz04M2I2NH8qFGUU2+NjvNM5PcAp3Al8/F8C15eYHCHBD46zbJCLF/MeFDxNRJlTMZSNmCcHQ2wAfAcOaDNAw9Dj/4sv4M0ni/EYbgPGGY0ZPmvgHoWoMZi8yKESiWykf1G+Ek+b+8qmIhxGowJ3dfweCRFAZTamvSrXii+NHiCBumTmJ/40utlDdSKTYx2In/4iD++PyXBM4sAoRNo91fd2cM0FHGS/37zyXjcMh4qrT0aNQTcIZrulvk1Rvk42aVaKP2RUVjbiNWK3JlKfXF/bU2/h8u+WPT3Fv6kgRgT2O8g2v+yI/gyGKAgC/fb4xxB/oTGC2UWL6QtfiZ0XiIXE2xHq02qhq+b5FEMnzgo60/T0/jdQYa8U=
  - secure: oeH44hNgwudS7KHqTtau0YKerqllm/FY7MKvz/ipNyegV6Q2Cw5owLJO70hUtjKwL2inu9hoPdDrWOsN4vu8E6qd+lExuas/CfzF/AZsWxb2CbPAXrAQb06m4/iiq3nGByKCIRZffBvfZtfNkOzj3J2lHRT8Fab3xw18LtI0l8o6DuCi9zmplBsfVF/qJtMrVk4y+eIPIHsaWES3bKIG+eo7xgdaWuANQ209Ye9lpycW3I9465q1Aa/tBuL23eMH/fZP+rVs6ekpGJ67y1VT8QyZv0+mQBQ0mTlsm2dg5Y8h3BxUSzyixoCIhw0jk49GBfKsE0ySE5uCSJ75OEWjRdqHC4L/nWw/QfZiI2dfUVSjmIXeSoE3b3nSS1KJaaOpCfuEbXUgiK0hhxXk517RvQ+/woC/5b9k1WHUocQn5FeI55TaNNiXb60gkINzHYDLMkCjQARX6NCJy7MvnizxEqxU7rUidziIEM0Ij0qREBsTlKANGKW2qLRPafjKHGQ/3nQmuZFC6OWW+kYgMFI9ZWfuXuOIkmL3Jt59SxJdS02riqCX3/zN3vMxihWl2Yr6Uu+WruEfBf8sRbMedvz8WNu/5kvgBFdjWctajSf3W61qag26Pjdy6aCZBc9vYR24w2nWYFj5CZ2uf40Y4JDP2jm4FSRUjSvCNtOMITYXENw=
  - secure: XlOfZJ0oiVMid2/75VvOy5AQe0SqSJv8T9xylL2FyW/5Gh2/Em9+087FiXrszaoPh6crKTeyxCaCOQA9jNNcvRpy9BmK9A88CUn0SPu1rZVrtQwAXlFSAQCRZjo80yEAxuR5axlUJOX+kA3gJr1rwfPTBHfcTqUedlzZlcuZpXMUVZdPaF/2H5pgP2TnTcDvnC1HgRdMVju2Dz9XqsgVaELqhKnfJ3zuQ34mqSvfqSlHupaJwMdJq0kQGiNTO5rEf9NxO0jZWxOuAH2AEQuNqHtQsqgU9ndL7OegpxS0JRTs3N/MPP9Vd1Hr4GnJnLbe2tj64uF7990/6gDcWjv9RDGVv0AUx5m6byOQJzWUecx34HLD9SNLUOJSYrs470Il6zQkwf2UVuix8r46A2GrnobGa7n1AM7VLxMe9h/lBvMbScNrkr5X4/U1+iBWJfR+MOzYaS0MzCu7G3ZPdKN62VXIZifGIRqcS8ZpmeieDd3I0pa2w8Rz4A0NAiHZCahNnI+Xg8Py+Kt8wz//RtqLEuglhlUCpDIa/SoksslIf46yaFN8nVOsnbaoYdDL+ueMqpTvexv6Y+sRtUVzFlwG8dlRi1lyETRBH0oWJXy+CDkjGIjq9unxzwKEcE7PSS272KFUbOkYySyAOa7UJQ7RKN+JuUbrywQeSH6S0mE0t5k=
before_install:
- nvm install 6.10
install:
- npm install -g serverless
script:
- mkdir artifacts
- cd status-monitor
- sbt assembly
- cd -
- cp status-monitor/target/scala-2.12/status-monitor.jar artifacts/status-monitor.jar
- cd newman
- npm install
- zip -qur ../artifacts/newman.zip handler.js package.json node_modules/
- cd -
deploy:
- provider: script
  script:
  - serverless deploy
  skip_cleanup: true
